// <auto-generated />
using JWTAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JWTAPI.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20200502151458_kitaplar")]
    partial class kitaplar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JWTAPI.Models.AAlt_Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SubC_Id");

                    b.HasKey("Id");

                    b.ToTable("AAlt_Kategoriler");

                    b.HasData(
                        new { Id = 1, Name = "Roman", SubC_Id = 1 },
                        new { Id = 2, Name = "Şiir", SubC_Id = 1 },
                        new { Id = 3, Name = "Deneme/Yazın", SubC_Id = 1 },
                        new { Id = 4, Name = "Türk Öykü", SubC_Id = 1 },
                        new { Id = 5, Name = "Edebiyat İnceleme", SubC_Id = 1 },
                        new { Id = 6, Name = "Biyografi & Oto Biyografi", SubC_Id = 1 },
                        new { Id = 7, Name = "Türk Günlük Anı", SubC_Id = 1 },
                        new { Id = 8, Name = "Aylık Dergi", SubC_Id = 1 },
                        new { Id = 9, Name = "Anlatı", SubC_Id = 1 },
                        new { Id = 10, Name = "Dünya Öykü", SubC_Id = 1 },
                        new { Id = 11, Name = "Dünya Günlük Anı", SubC_Id = 1 },
                        new { Id = 12, Name = "Söyleşi", SubC_Id = 1 },
                        new { Id = 13, Name = "Türk Mektup", SubC_Id = 1 },
                        new { Id = 14, Name = "Edebiyatçılar", SubC_Id = 1 },
                        new { Id = 15, Name = "Destan", SubC_Id = 1 },
                        new { Id = 16, Name = "Dünya Mektup", SubC_Id = 1 },
                        new { Id = 17, Name = "Röportaj", SubC_Id = 1 },
                        new { Id = 18, Name = "Antoloji", SubC_Id = 1 },
                        new { Id = 19, Name = "Halk Ozanları", SubC_Id = 1 },
                        new { Id = 20, Name = "Almanak", SubC_Id = 1 }
                    );
                });

            modelBuilder.Entity("JWTAPI.Models.Alt_Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category_Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar");

                    b.HasData(
                        new { Id = 1, Category_Id = 1, Name = "Edebiyat" },
                        new { Id = 2, Category_Id = 1, Name = "Çocuk ve Gençlik" },
                        new { Id = 3, Category_Id = 1, Name = "Eğitim Başvuru" },
                        new { Id = 4, Category_Id = 1, Name = "Araştırma - Tarih" },
                        new { Id = 5, Category_Id = 1, Name = "Din Tasavvuf" },
                        new { Id = 6, Category_Id = 1, Name = "Foreign Languages" },
                        new { Id = 7, Category_Id = 1, Name = "Ders/Sınav Kitapları" },
                        new { Id = 8, Category_Id = 1, Name = "Sanat - Tasarım" },
                        new { Id = 9, Category_Id = 1, Name = "Felsefe" },
                        new { Id = 10, Category_Id = 1, Name = "Çizgi Roman" },
                        new { Id = 11, Category_Id = 1, Name = "Hobi" },
                        new { Id = 12, Category_Id = 1, Name = "Bilim" },
                        new { Id = 13, Category_Id = 1, Name = "Mizah" },
                        new { Id = 14, Category_Id = 1, Name = "Prestij Kitapları" },
                        new { Id = 15, Category_Id = 1, Name = "Mitoloji Efsane" },
                        new { Id = 16, Category_Id = 1, Name = "Sesli Kitaplar" }
                    );
                });

            modelBuilder.Entity("JWTAPI.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new { Id = 1, Name = "Kitap" },
                        new { Id = 2, Name = "E-Kitap" },
                        new { Id = 3, Name = "Elektronik" },
                        new { Id = 4, Name = "Hobi & Oyuncak" },
                        new { Id = 5, Name = "Kırtasiye" },
                        new { Id = 6, Name = "Oyun & Konsol" },
                        new { Id = 7, Name = "Müzik" },
                        new { Id = 8, Name = "Dergi" },
                        new { Id = 9, Name = "Hediyelik Eşyalar" },
                        new { Id = 10, Name = "Spor & Outdoor" },
                        new { Id = 11, Name = "Çok Satanlar" },
                        new { Id = 12, Name = "Yeni Çıkan Kitaplar" },
                        new { Id = 13, Name = "Yazarlar" },
                        new { Id = 14, Name = "Yayınevleri" }
                    );
                });

            modelBuilder.Entity("JWTAPI.Models.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Sepettekiler");
                });

            modelBuilder.Entity("JWTAPI.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Photo");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new { Id = 1, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_u_x_851x373_anneler_gunu_lp.jpg" },
                        new { Id = 2, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_t_40_851x373_cep_telefonu.jpg" },
                        new { Id = 3, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/ramazan-ana-sayfa.jpg" },
                        new { Id = 4, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_u_x_851x373_lego_cocukluk_hayalim.jpg" },
                        new { Id = 5, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_u_15_851x373_mayis_oyuncak_lp.jpg" },
                        new { Id = 6, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_u_x_851x373_ayin_yayinevi_tudem.jpg" },
                        new { Id = 7, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_u_14_851x373_mayis_teknoloji_lp.jpg" },
                        new { Id = 8, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0320_d_u_x_851x373_haftanin_firsati_salon.jpg" },
                        new { Id = 9, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/tum-kitap-kampanyalari-homepage1.jpg" },
                        new { Id = 10, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/0420_d_u_2_851x373_twin_il_evde_ogrenmek_rev.jpg" },
                        new { Id = 11, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/19dca320-5fa9-0138-c9d9-22000a0cc917-1586777858-379915.jpg" },
                        new { Id = 12, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/851x373_PeriliKosk.png" },
                        new { Id = 13, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/bd-films-homepage.jpg" },
                        new { Id = 14, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/dergi_851x373_mayis.png" },
                        new { Id = 15, Photo = "https://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/taksit-sevenekleri-yeni.jpg" }
                    );
                });

            modelBuilder.Entity("JWTAPI.Models.UrunKitapAyrıntı", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Dimensions");

                    b.Property<int>("DoughType");

                    b.Property<string>("Explanation");

                    b.Property<int>("FirstYear");

                    b.Property<string>("Language");

                    b.Property<int>("PageNumber");

                    b.Property<int>("PrintNumber");

                    b.HasKey("UrunId");

                    b.ToTable("UKitapAyrıntıları");
                });

            modelBuilder.Entity("JWTAPI.Models.Ürün_Diğer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<int>("Discount");

                    b.Property<string>("Name");

                    b.Property<string>("P_Type");

                    b.Property<string>("Photo");

                    b.Property<double>("Point");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Ürün_Diğerleri");
                });

            modelBuilder.Entity("JWTAPI.Models.Ürün_Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("CoverType");

                    b.Property<int>("Discount");

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.Property<double>("Point");

                    b.Property<double>("Price");

                    b.Property<string>("Publisher");

                    b.Property<int>("SubC_Id");

                    b.HasKey("Id");

                    b.ToTable("Ürün_Kitaplar");

                    b.HasData(
                        new { Id = 1, Author = "Nilgün Bodur", CoverType = "İnce Kapak", Discount = 37, Name = "Akıllandım Artık Şimdi Daha Deliyim", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001869654001-1.jpg", Point = 2.0, Price = 16.38, Publisher = "Destek Yayınları", SubC_Id = 1 },
                        new { Id = 2, Author = "Vianna Stibal", CoverType = "İnce Kapak", Discount = 25, Name = "Theta Healing-Derin İnançları Bulun", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001870519001-1.jpg", Point = 0.0, Price = 17.25, Publisher = "Kitap", SubC_Id = 1 },
                        new { Id = 3, Author = "Kemal Sayar", CoverType = "İnce Kapak", Discount = 30, Name = "Kaygı Çağı-Salgın Zamanında Ruh Sağlığı", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001870287001-1.jpg", Point = 0.0, Price = 20.3, Publisher = "Kapı Yayınları", SubC_Id = 1 },
                        new { Id = 4, Author = "Greer Hendricks", CoverType = "Ciltli", Discount = 35, Name = "İsimsiz Kız", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001863427001-1.jpg", Point = 0.0, Price = 27.3, Publisher = "Ephesus Yayınları", SubC_Id = 1 },
                        new { Id = 5, Author = "Zülfü Livaneli", CoverType = "İnce Kapak", Discount = 30, Name = "Konstantiniyye Oteli", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001870779001-1.jpg", Point = 0.0, Price = 24.5, Publisher = "İnkılap Kitabevi", SubC_Id = 1 },
                        new { Id = 6, Author = "Katsuhiro Otomo", CoverType = "İnce Kapak", Discount = 25, Name = "Akira 1.Cilt", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001870778001-1.jpg", Point = 0.0, Price = 51.0, Publisher = "Gerekli Şeyler", SubC_Id = 1 },
                        new { Id = 7, Author = "Alex Hirsch", CoverType = "Ciltli", Discount = 35, Name = "Disney Esrarengiz Kasaba-Günlük 3", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001849287001-1.jpg", Point = 3.5, Price = 58.18, Publisher = "Beta Kids", SubC_Id = 1 },
                        new { Id = 8, Author = "Soren Kierkegaard", CoverType = "İnce Kapak", Discount = 30, Name = "Ya-Ya Da", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001868366001-1.jpg", Point = 0.0, Price = 48.3, Publisher = "Alfa Yayıncılık", SubC_Id = 1 },
                        new { Id = 9, Author = "M.Rise", CoverType = "Ciltli", Discount = 37, Name = "Sesini Duyur", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001868717001-1.jpg", Point = 5.0, Price = 26.46, Publisher = "Ephesus Yayınları", SubC_Id = 1 },
                        new { Id = 10, Author = "Hayati Sır", CoverType = "İnce Kapak", Discount = 42, Name = "İlahi Aşk Seti-10 Kitap Takım", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001869472001-1.jpg", Point = 0.0, Price = 107.28, Publisher = "Hayykitap", SubC_Id = 1 },
                        new { Id = 11, Author = "Tuğçe Işınsu", CoverType = "İnce Kapak", Discount = 30, Name = "Tuğçe Işınsu Çok Satan Kitaplar Seti-2 Kitap Takım", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001868573001-1.jpg", Point = 2.0, Price = 43.4, Publisher = "Feniks Kitap", SubC_Id = 1 },
                        new { Id = 12, Author = "Sine Boran Art", CoverType = "İnce Kapak", Discount = 30, Name = "Çerkes Kızından Tarifler", Photo = "https://i.dr.com.tr/cache/154x170-0/originals/0001690945002-1.jpg", Point = 2.5, Price = 45.5, Publisher = "İş Bankası", SubC_Id = 1 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
